[package]
name = "gameboy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"
bitmatch = "0.1.1"
indoc = "2.0.5"
macroquad = "0.4.13"
morton-encoding = "2.0.1"
rstest = "0.23.0"
